// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6.Models;

namespace Mission6.Migrations
{
    [DbContext(typeof(MoviesContext))]
    [Migration("20230210010613_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6.Models.MovieModel", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Action/Sci-Fi",
                            Director = "George Lucas",
                            Edited = false,
                            LentTo = "",
                            Notes = "Favorite Movie",
                            Rating = "PG-13",
                            Title = "Star Wars III - Revenge of the Sith",
                            Year = (ushort)2005
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Comedy/Teen",
                            Director = "Greg Mottola",
                            Edited = false,
                            LentTo = "",
                            Notes = "Funny and a little bad",
                            Rating = "R",
                            Title = "Superbad",
                            Year = (ushort)2007
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Action/Sci-Fi",
                            Director = "Taika Waititi",
                            Edited = false,
                            LentTo = "",
                            Notes = "Great superhero movie",
                            Rating = "PG-13",
                            Title = "Thor: Ragnarok",
                            Year = (ushort)2017
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
